"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { api, CartItem, cartTotal, money, readCart, writeCart } from "../../lib/shop";

const emptyForm = { customer_name: "", phone: "", email: "", district: "Баянзүрх", khoroo: "", address: "", note: "", payment_method: "cash" };
export default function Checkout() {
  const [items, setItems] = useState<CartItem[]>(() => readCart()); const [form, setForm] = useState(emptyForm); const [order, setOrder] = useState<{ order_number: string; total: string } | null>(null); const [error, setError] = useState("");
  const update = (id: number, quantity: number) => { const next = items.map((item) => item.id === id ? { ...item, quantity: Math.max(0, quantity) } : item).filter((item) => item.quantity > 0); setItems(next); writeCart(next); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); const response = await fetch(`${api}/orders`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ ...form, items: items.map(({ id, quantity }) => ({ product_id: id, quantity })) }) }); const result = await response.json(); if (!response.ok) { setError(result.message || "Захиалга үүсгэхэд алдаа гарлаа."); return; } setOrder(result.data); writeCart([]); setItems([]); };
  if (order) return <main className="checkout-page"><div className="checkout-card"><p className="eyebrow">Захиалга баталгаажлаа</p><h1>Баярлалаа.</h1><p>Таны захиалгын дугаар: <strong>{order.order_number}</strong></p><p>Нийт төлөх дүн: <strong>{money(order.total)}</strong></p><Link className="primary" href="/">Дэлгүүр рүү буцах</Link></div></main>;
  return <main className="checkout-page"><header className="site-header"><Link className="brand" href="/">ЖИЖИГ<span>SHOP</span></Link><Link href="/">← Худалдан авалт үргэлжлүүлэх</Link></header><div className="checkout-layout"><section><p className="eyebrow">Захиалга</p><h1>Хүргэлтийн мэдээлэл</h1>{items.length === 0 ? <p className="notice">Таны сагс хоосон байна. <Link href="/">Бүтээгдэхүүн үзэх</Link></p> : <form onSubmit={submit} className="checkout-form">{Object.entries({ customer_name: "Овог нэр", phone: "Утас", email: "Имэйл", district: "Хот / дүүрэг", khoroo: "Хороо", address: "Дэлгэрэнгүй хаяг", note: "Нэмэлт тайлбар" }).map(([key, label]) => <label key={key}>{label}<input required={!['email', 'note'].includes(key)} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label>Төлбөрийн хэлбэр<select value={form.payment_method} onChange={(event) => setForm({ ...form, payment_method: event.target.value })}><option value="cash">Хүргэлтээр бэлнээр</option><option value="bank_transfer">Банкны шилжүүлэг</option><option value="qpay">Онлайн төлбөр</option></select></label>{error && <p className="error">{error}</p>}<button className="primary" type="submit">Захиалга баталгаажуулах</button></form>}</section><aside className="order-summary"><h2>Таны сагс</h2>{items.map((item) => <div className="summary-line" key={item.id}><span>{item.name} × {item.quantity}</span><strong>{money(Number(item.sale_price ?? item.price) * item.quantity)}</strong><button onClick={() => update(item.id, 0)}>Устгах</button></div>)}<hr /><div className="summary-total"><span>Барааны дүн</span><strong>{money(cartTotal(items))}</strong></div><div className="summary-total"><span>Хүргэлт</span><strong>{items.length ? money(5000) : money(0)}</strong></div><div className="summary-total"><span>Нийт</span><strong>{money(cartTotal(items) + (items.length ? 5000 : 0))}</strong></div></aside></div></main>;
}