"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { api, Category, Product, money } from "../../lib/shop";

type Order = { id: number; order_number: string; customer_name: string; total: string; status: string };
const statuses = ["NEW", "CONFIRMED", "PAID", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED"];
export default function Admin() {
  const [token, setToken] = useState(() => typeof window !== "undefined" ? localStorage.getItem("admin-token") ?? "" : ""); const [email, setEmail] = useState("admin@example.com"); const [password, setPassword] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [name, setName] = useState(""); const [categoryId, setCategoryId] = useState(""); const [price, setPrice] = useState(""); const [stock, setStock] = useState("10"); const [message, setMessage] = useState("");
  const headers = () => ({ Accept: "application/json", Authorization: `Bearer ${token}`, "Content-Type": "application/json" });
  const load = useCallback(async () => { const options = { headers: { Accept: "application/json", Authorization: `Bearer ${token}`, "Content-Type": "application/json" } }; const [p, c, o] = await Promise.all([fetch(`${api}/admin/products`, options), fetch(`${api}/admin/categories`, options), fetch(`${api}/admin/orders`, options)]); const [productsResult, categoriesResult, ordersResult] = await Promise.all([p.json(), c.json(), o.json()]); setProducts(productsResult.data?.data ?? []); setCategories(categoriesResult.data ?? []); setOrders(ordersResult.data?.data ?? []); }, [token]);
  useEffect(() => { if (!token) return; const timer = window.setTimeout(() => { load().catch(() => setMessage("Админы мэдээлэл ачаалж чадсангүй.")); }, 0); return () => window.clearTimeout(timer); }, [token, load]);
  const login = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`${api}/auth/login`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ email, password }) }); const result = await response.json(); if (!response.ok) { setMessage(result.message); return; } localStorage.setItem("admin-token", result.data.token); setToken(result.data.token); };
  const createProduct = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`${api}/admin/products`, { method: "POST", headers: headers(), body: JSON.stringify({ name, category_id: Number(categoryId), price: Number(price), stock: Number(stock), sku: `SKU-${Date.now()}`, status: true }) }); if (response.ok) { setName(""); setPrice(""); setMessage("Бүтээгдэхүүн нэмэгдлээ."); load(); } else setMessage("Бүтээгдэхүүн нэмэхэд алдаа гарлаа."); };
  const updateOrder = async (order: Order, status: string) => { await fetch(`${api}/admin/orders/${order.id}`, { method: "PUT", headers: headers(), body: JSON.stringify({ status }) }); load(); };
  if (!token) return <main className="admin-page"><form className="checkout-card login-card" onSubmit={login}><p className="eyebrow">Удирдлагын хэсэг</p><h1>Нэвтрэх</h1><label>Имэйл<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Нууц үг<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{message && <p className="error">{message}</p>}<button className="primary">Нэвтрэх</button></form></main>;
  return <main className="admin-page"><header className="site-header"><Link className="brand" href="/">ЖИЖИГ<span>SHOP</span></Link><button onClick={() => { localStorage.removeItem("admin-token"); setToken(""); }}>Гарах</button></header><div className="admin-grid"><section><p className="eyebrow">Удирдлага</p><h1>Дэлгүүрийн самбар</h1><div className="admin-stats"><strong>{products.length}<small>Бүтээгдэхүүн</small></strong><strong>{orders.length}<small>Захиалга</small></strong><strong>{categories.length}<small>Ангилал</small></strong></div><h2>Бүтээгдэхүүн нэмэх</h2><form className="admin-form" onSubmit={createProduct}><input required placeholder="Нэр" value={name} onChange={(event) => setName(event.target.value)} /><select required value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Ангилал сонгох</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input required type="number" placeholder="Үнэ" value={price} onChange={(event) => setPrice(event.target.value)} /><input required type="number" placeholder="Үлдэгдэл" value={stock} onChange={(event) => setStock(event.target.value)} /><button className="primary">Нэмэх</button></form><h2>Бүтээгдэхүүний жагсаалт</h2>{products.map((product) => <div className="admin-row" key={product.id}><span>{product.name}</span><strong>{money(product.sale_price ?? product.price)}</strong></div>)}</section><aside><h2>Сүүлийн захиалгууд</h2>{orders.map((order) => <div className="admin-order" key={order.id}><strong>{order.order_number}</strong><span>{order.customer_name} · {money(order.total)}</span><select value={order.status} onChange={(event) => updateOrder(order, event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></div>)}</aside></div></main>;
}